steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/express-database", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/express-database"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
        [
          "run",
          "deploy",
          "firestoredatabase",
          "--image",
          "gcr.io/$PROJECT_ID/express-database",
          "--region",
          "australia-southeast1",
          "--platform",
          "managed",
        ]
  images:
    - gcr.io/$PROJECT_ID/express-database
  